name: Release npm Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clear npm Cache (Optional)
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install
        env:
          # Set a custom cache location if needed
          npm_config_cache: ~/.npm-cache

      - name: Clean Previous Build
        run: rm -rf dist/

      - name: Build Package
        run: npm run build

      - name: Publish to npm
        run: |
          npm publish --access public
          echo "## npm Package Published" >> $GITHUB_STEP_SUMMARY
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
